version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - '.data:/data/db'
  webapp:
    image: ${RELEASE_IMAGE_NAME}
    environment:
      CORS_WHITELIST: 'http://example.com/'
      MONGODB_URI: 'mongodb://mongo:27017/'
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
